import { PartOfSpeech, WordCard } from './types';

export const VOCABULARY: WordCard[] = [
  // --- Page 1: Nouns (名词类) ---
  { id: 'p1_1', english: 'blackboard', chinese: '黑板', pos: PartOfSpeech.Noun },
  { id: 'p1_2', english: 'honey', chinese: '蜂蜜', pos: PartOfSpeech.Noun },
  { id: 'p1_3', english: 'blackbird', chinese: '黑鹂', pos: PartOfSpeech.Noun },
  { id: 'p1_4', english: 'morning', chinese: '早晨', pos: PartOfSpeech.Noun },
  { id: 'p1_5', english: 'home', chinese: '家', pos: PartOfSpeech.Noun },
  { id: 'p1_6', english: 'greetings', chinese: '问候', pos: PartOfSpeech.Noun },
  { id: 'p1_7', english: 'China', chinese: '中国', pos: PartOfSpeech.Noun },
  { id: 'p1_8', english: 'wing', chinese: '翅膀', pos: PartOfSpeech.Noun },
  { id: 'p1_9', english: 'evening', chinese: '傍晚', pos: PartOfSpeech.Noun },
  { id: 'p1_10', english: 'door', chinese: '门', pos: PartOfSpeech.Noun },
  { id: 'p1_11', english: 'class', chinese: '班级', pos: PartOfSpeech.Noun },
  { id: 'p1_12', english: 'photo', chinese: '照片', pos: PartOfSpeech.Noun },
  { id: 'p1_13', english: 'chair', chinese: '椅子', pos: PartOfSpeech.Noun },
  { id: 'p1_14', english: 'hill', chinese: '小山', pos: PartOfSpeech.Noun },
  { id: 'p1_15', english: 'English', chinese: '英语', pos: PartOfSpeech.Noun },
  { id: 'p1_16', english: 'desk', chinese: '书桌', pos: PartOfSpeech.Noun },
  { id: 'p1_17', english: 'house', chinese: '房子', pos: PartOfSpeech.Noun },
  { id: 'p1_18', english: 'floor', chinese: '地板', pos: PartOfSpeech.Noun },

  // --- Page 2: Nouns (名词类) ---
  { id: 'p2_1', english: 'classroom', chinese: '教室', pos: PartOfSpeech.Noun },
  { id: 'p2_2', english: 'sister', chinese: '姐妹', pos: PartOfSpeech.Noun },
  { id: 'p2_3', english: 'ball', chinese: '球', pos: PartOfSpeech.Noun },
  { id: 'p2_4', english: 'schoolbag', chinese: '书包', pos: PartOfSpeech.Noun },
  { id: 'p2_5', english: 'brother', chinese: '兄弟', pos: PartOfSpeech.Noun },
  { id: 'p2_6', english: 'eraser', chinese: '橡皮', pos: PartOfSpeech.Noun },
  { id: 'p2_7', english: 'turtle', chinese: '海龟', pos: PartOfSpeech.Noun },
  { id: 'p2_8', english: 'family', chinese: '家庭', pos: PartOfSpeech.Noun },
  { id: 'p2_9', english: 'ruler', chinese: '尺子', pos: PartOfSpeech.Noun },
  { id: 'p2_10', english: 'dog', chinese: '狗', pos: PartOfSpeech.Noun },
  { id: 'p2_11', english: 'dad', chinese: '爸爸', pos: PartOfSpeech.Noun },
  { id: 'p2_12', english: 'bird', chinese: '鸟', pos: PartOfSpeech.Noun },
  { id: 'p2_13', english: 'hen', chinese: '母鸡', pos: PartOfSpeech.Noun },
  { id: 'p2_14', english: 'arm', chinese: '手臂', pos: PartOfSpeech.Noun },
  { id: 'p2_15', english: 'pet', chinese: '宠物', pos: PartOfSpeech.Noun },
  { id: 'p2_16', english: 'cat', chinese: '猫', pos: PartOfSpeech.Noun },
  { id: 'p2_17', english: 'mum', chinese: '妈妈', pos: PartOfSpeech.Noun },
  { id: 'p2_18', english: 'fish', chinese: '鱼', pos: PartOfSpeech.Noun },

  // --- Page 3: Nouns (名词类) ---
  { id: 'p3_1', english: 'animal', chinese: '动物', pos: PartOfSpeech.Noun },
  { id: 'p3_2', english: 'bee', chinese: '蜜蜂', pos: PartOfSpeech.Noun },
  { id: 'p3_3', english: 'nose', chinese: '鼻子', pos: PartOfSpeech.Noun },
  { id: 'p3_4', english: 'eye(s)', chinese: '眼睛', pos: PartOfSpeech.Noun },
  { id: 'p3_5', english: 'mouth', chinese: '嘴巴', pos: PartOfSpeech.Noun },
  { id: 'p3_6', english: 'pencil case', chinese: '铅笔盒', pos: PartOfSpeech.Noun },
  { id: 'p3_7', english: 'face', chinese: '脸', pos: PartOfSpeech.Noun },
  { id: 'p3_8', english: 'time', chinese: '时间', pos: PartOfSpeech.Noun },
  { id: 'p3_9', english: 'afternoon', chinese: '下午', pos: PartOfSpeech.Noun },
  { id: 'p3_10', english: 'horse', chinese: '马', pos: PartOfSpeech.Noun },
  { id: 'p3_11', english: 'pencil', chinese: '铅笔', pos: PartOfSpeech.Noun },
  { id: 'p3_12', english: 'egg', chinese: '鸡蛋', pos: PartOfSpeech.Noun },
  { id: 'p3_13', english: 'friend', chinese: '朋友', pos: PartOfSpeech.Noun },
  { id: 'p3_14', english: 'name', chinese: '名字', pos: PartOfSpeech.Noun },
  { id: 'p3_15', english: 'day', chinese: '天/日子', pos: PartOfSpeech.Noun },
  { id: 'p3_16', english: 'book', chinese: '书', pos: PartOfSpeech.Noun },
  { id: 'p3_17', english: 'heart', chinese: '心', pos: PartOfSpeech.Noun },
  { id: 'p3_18', english: 'ear(s)', chinese: '耳朵', pos: PartOfSpeech.Noun },

  // --- Page 4: Nouns (名词类) ---
  { id: 'p4_1', english: 'school', chinese: '学校', pos: PartOfSpeech.Noun },
  { id: 'p4_2', english: 'mother', chinese: '母亲', pos: PartOfSpeech.Noun },
  { id: 'p4_3', english: 'father', chinese: '父亲', pos: PartOfSpeech.Noun },
  { id: 'p4_4', english: 'grandfather', chinese: '祖父/爷爷', pos: PartOfSpeech.Noun },
  { id: 'p4_5', english: 'grandmother', chinese: '祖母/奶奶', pos: PartOfSpeech.Noun },
  { id: 'p4_6', english: 'food', chinese: '食物', pos: PartOfSpeech.Noun },
  { id: 'p4_7', english: 'story', chinese: '故事', pos: PartOfSpeech.Noun },
  { id: 'p4_8', english: 'spoon', chinese: '勺子', pos: PartOfSpeech.Noun },
  { id: 'p4_9', english: 'lunch box', chinese: '午餐盒', pos: PartOfSpeech.Noun },
  { id: 'p4_10', english: 'shoelaces', chinese: '鞋带', pos: PartOfSpeech.Noun },
  { id: 'p4_11', english: 'bag', chinese: '包', pos: PartOfSpeech.Noun },
  { id: 'p4_12', english: 'number', chinese: '数字', pos: PartOfSpeech.Noun },
  { id: 'p4_13', english: 'duck', chinese: '鸭子', pos: PartOfSpeech.Noun },
  { id: 'p4_14', english: 'flag', chinese: '旗帜', pos: PartOfSpeech.Noun },
  { id: 'p4_15', english: 'key', chinese: '钥匙', pos: PartOfSpeech.Noun },
  { id: 'p4_16', english: 'whistle', chinese: '哨子', pos: PartOfSpeech.Noun },
  { id: 'p4_17', english: 'sports field', chinese: '运动场', pos: PartOfSpeech.Noun },
  { id: 'p4_18', english: 'hula hoop', chinese: '呼啦圈', pos: PartOfSpeech.Noun },

  // --- Page 5: Verbs (动词类) ---
  { id: 'p5_1', english: 'is', chinese: '是', pos: PartOfSpeech.Verb },
  { id: 'p5_2', english: 'am', chinese: '是', pos: PartOfSpeech.Verb },
  { id: 'p5_3', english: 'are', chinese: '是', pos: PartOfSpeech.Verb },
  { id: 'p5_4', english: 'can', chinese: '能/会', pos: PartOfSpeech.Verb },
  { id: 'p5_5', english: 'learn', chinese: '学习', pos: PartOfSpeech.Verb },
  { id: 'p5_6', english: 'welcome', chinese: '欢迎', pos: PartOfSpeech.Verb },
  { id: 'p5_7', english: 'meet', chinese: '遇见', pos: PartOfSpeech.Verb },
  { id: 'p5_8', english: 'make', chinese: '制作', pos: PartOfSpeech.Verb },
  { id: 'p5_9', english: 'put', chinese: '放', pos: PartOfSpeech.Verb },
  { id: 'p5_10', english: 'sit', chinese: '坐', pos: PartOfSpeech.Verb },
  { id: 'p5_11', english: 'lay', chinese: '躺/下蛋', pos: PartOfSpeech.Verb },
  { id: 'p5_12', english: 'clean', chinese: '打扫', pos: PartOfSpeech.Verb }, // Removed asterisk
  { id: 'p5_13', english: 'try', chinese: '尝试', pos: PartOfSpeech.Verb },
  { id: 'p5_14', english: 'stay', chinese: '停留', pos: PartOfSpeech.Verb },
  { id: 'p5_15', english: 'fly', chinese: '飞', pos: PartOfSpeech.Verb },
  { id: 'p5_16', english: 'let', chinese: '让', pos: PartOfSpeech.Verb },
  { id: 'p5_17', english: 'design', chinese: '设计', pos: PartOfSpeech.Verb },
  { id: 'p5_18', english: 'look', chinese: '看', pos: PartOfSpeech.Verb },

  // --- Page 6: Verbs (动词类) ---
  { id: 'p6_1', english: 'pack', chinese: '打包', pos: PartOfSpeech.Verb },
  { id: 'p6_2', english: 'find', chinese: '找到', pos: PartOfSpeech.Verb },
  { id: 'p6_3', english: 'love', chinese: '爱', pos: PartOfSpeech.Verb }, // Removed asterisk
  { id: 'p6_4', english: 'see', chinese: '看见', pos: PartOfSpeech.Verb },
  { id: 'p6_5', english: 'draw', chinese: '画', pos: PartOfSpeech.Verb },
  { id: 'p6_6', english: 'use', chinese: '使用', pos: PartOfSpeech.Verb },
  { id: 'p6_7', english: 'take', chinese: '拿/带', pos: PartOfSpeech.Verb },
  { id: 'p6_8', english: 'help', chinese: '帮助', pos: PartOfSpeech.Verb },
  { id: 'p6_9', english: 'worry', chinese: '担心', pos: PartOfSpeech.Verb },
  { id: 'p6_10', english: 'show', chinese: '展示', pos: PartOfSpeech.Verb },
  { id: 'p6_11', english: 'have', chinese: '有', pos: PartOfSpeech.Verb },
  { id: 'p6_12', english: 'flap', chinese: '拍打(翅膀)', pos: PartOfSpeech.Verb },
  { id: 'p6_13', english: 'do', chinese: '做', pos: PartOfSpeech.Verb },
  { id: 'p6_14', english: 'ride', chinese: '骑', pos: PartOfSpeech.Verb },
  { id: 'p6_15', english: 'go', chinese: '去', pos: PartOfSpeech.Verb },
  { id: 'p6_16', english: 'act', chinese: '表演/行动', pos: PartOfSpeech.Verb },
  { id: 'p6_17', english: 'wash', chinese: '洗', pos: PartOfSpeech.Verb },
  { id: 'p6_18', english: 'tie', chinese: '系/打结', pos: PartOfSpeech.Verb },

  // --- Page 7: Verbs (动词类) ---
  { id: 'p7_1', english: 'say', chinese: '说', pos: PartOfSpeech.Verb },
  { id: 'p7_2', english: 'skip', chinese: '跳绳/跳跃', pos: PartOfSpeech.Verb },
  { id: 'p7_3', english: 'watch', chinese: '观看', pos: PartOfSpeech.Verb },
  { id: 'p7_4', english: 'play', chinese: '玩', pos: PartOfSpeech.Verb },
  { id: 'p7_5', english: 'walk', chinese: '走', pos: PartOfSpeech.Verb },

  // --- Page 8: Adjectives (形容词类) ---
  { id: 'p8_1', english: 'small', chinese: '小的', pos: PartOfSpeech.Adjective },
  { id: 'p8_2', english: 'lovely', chinese: '可爱的', pos: PartOfSpeech.Adjective },
  { id: 'p8_3', english: 'first', chinese: '第一的', pos: PartOfSpeech.Adjective },
  { id: 'p8_4', english: 'new', chinese: '新的', pos: PartOfSpeech.Adjective },
  { id: 'p8_5', english: 'fine', chinese: '好的/晴朗的', pos: PartOfSpeech.Adjective },
  { id: 'p8_6', english: 'happy', chinese: '快乐的', pos: PartOfSpeech.Adjective },
  { id: 'p8_7', english: 'round', chinese: '圆的', pos: PartOfSpeech.Adjective },
  { id: 'p8_8', english: 'funny', chinese: '滑稽的', pos: PartOfSpeech.Adjective },
  { id: 'p8_9', english: 'dirty', chinese: '脏的', pos: PartOfSpeech.Adjective },
  { id: 'p8_10', english: 'big', chinese: '大的', pos: PartOfSpeech.Adjective },
  { id: 'p8_11', english: 'cute', chinese: '可爱的', pos: PartOfSpeech.Adjective },
  { id: 'p8_12', english: 'cozy', chinese: '舒适的', pos: PartOfSpeech.Adjective },
  { id: 'p8_13', english: 'high', chinese: '高的', pos: PartOfSpeech.Adjective },
  { id: 'p8_14', english: 'ready', chinese: '准备好的', pos: PartOfSpeech.Adjective },
  { id: 'p8_15', english: 'sad', chinese: '伤心的', pos: PartOfSpeech.Adjective },
  { id: 'p8_16', english: 'soft', chinese: '柔软的', pos: PartOfSpeech.Adjective },
  { id: 'p8_17', english: 'helpful', chinese: '有帮助的', pos: PartOfSpeech.Adjective },
  { id: 'p8_18', english: 'long', chinese: '长的', pos: PartOfSpeech.Adjective },

  // --- Page 9: Adjectives (形容词类) ---
  { id: 'p9_1', english: 'dear', chinese: '亲爱的', pos: PartOfSpeech.Adjective },
  { id: 'p9_2', english: 'nice', chinese: '美好的', pos: PartOfSpeech.Adjective },
  { id: 'p9_3', english: 'tall', chinese: '高的', pos: PartOfSpeech.Adjective },
  { id: 'p9_4', english: 'red', chinese: '红色的', pos: PartOfSpeech.Adjective },
  { id: 'p9_5', english: 'good', chinese: '好的', pos: PartOfSpeech.Adjective },
  { id: 'p9_6', english: 'little', chinese: '小的/年幼的', pos: PartOfSpeech.Adjective },
  { id: 'p9_7', english: 'fun', chinese: '有趣的', pos: PartOfSpeech.Adjective },

  // --- Page 10: Pronouns (人称代词) ---
  { id: 'p10_1', english: 'I', chinese: '我 (主格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_2', english: 'me', chinese: '我 (宾格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_3', english: 'my', chinese: '我的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_4', english: 'we', chinese: '我们 (主格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_5', english: 'us', chinese: '我们 (宾格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_6', english: 'our', chinese: '我们的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_7', english: 'you', chinese: '你/你们', pos: PartOfSpeech.Pronoun },
  { id: 'p10_8', english: 'your', chinese: '你的/你们的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_9', english: 'he', chinese: '他 (主格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_10', english: 'him', chinese: '他 (宾格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_11', english: 'his', chinese: '他的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_12', english: 'she', chinese: '她 (主格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_13', english: 'her', chinese: '她/她的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_14', english: 'they', chinese: '他们 (主格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_15', english: 'it', chinese: '它 (主格/宾格)', pos: PartOfSpeech.Pronoun },
  { id: 'p10_16', english: 'its', chinese: '它的', pos: PartOfSpeech.Pronoun },
  { id: 'p10_17', english: 'myself', chinese: '我自己', pos: PartOfSpeech.Pronoun },
  { id: 'p10_18', english: 'them', chinese: '他们 (宾格)', pos: PartOfSpeech.Pronoun },

  // --- Page 11: Prepositions (介词) ---
  { id: 'p11_1', english: 'on', chinese: '在...上面', pos: PartOfSpeech.Preposition },
  { id: 'p11_2', english: 'in', chinese: '在...里面', pos: PartOfSpeech.Preposition },
  { id: 'p11_3', english: 'with', chinese: '和...', pos: PartOfSpeech.Preposition },
  { id: 'p11_4', english: 'for', chinese: '为了/给', pos: PartOfSpeech.Preposition },

  // --- Page 11: Adverbs (副词) ---
  { id: 'p11_5', english: 'back', chinese: '回/向后', pos: PartOfSpeech.Adverb },
  { id: 'p11_6', english: 'away', chinese: '离开/远处', pos: PartOfSpeech.Adverb },
  { id: 'p11_7', english: 'too', chinese: '也/太', pos: PartOfSpeech.Adverb },
  { id: 'p11_8', english: 'now', chinese: '现在', pos: PartOfSpeech.Adverb },

  // --- Page 12: Others (其他类) ---
  { id: 'p12_1', english: 'hi', chinese: '嗨', pos: PartOfSpeech.Other },
  { id: 'p12_2', english: 'hello', chinese: '你好', pos: PartOfSpeech.Other },
  { id: 'p12_3', english: 'goodbye', chinese: '再见', pos: PartOfSpeech.Other },
  { id: 'p12_4', english: 'how', chinese: '怎样', pos: PartOfSpeech.Other },
  { id: 'p12_5', english: 'what', chinese: '什么', pos: PartOfSpeech.Other },
  { id: 'p12_6', english: 'who', chinese: '谁', pos: PartOfSpeech.Other },
  { id: 'p12_7', english: 'on duty', chinese: '值日', pos: PartOfSpeech.Other },
  { id: 'p12_8', english: 'sorry', chinese: '对不起', pos: PartOfSpeech.Other },
  { id: 'p12_9', english: 'Thank you.', chinese: '谢谢你', pos: PartOfSpeech.Other },
  { id: 'p12_10', english: 'You’re welcome.', chinese: '不客气', pos: PartOfSpeech.Other },
  { id: 'p12_11', english: 'this', chinese: '这个', pos: PartOfSpeech.Other },
  { id: 'p12_12', english: 'that', chinese: '那个', pos: PartOfSpeech.Other },
  { id: 'p12_13', english: 'and', chinese: '和', pos: PartOfSpeech.Other },
  { id: 'p12_14', english: 'Good job!', chinese: '做得好', pos: PartOfSpeech.Other },
  { id: 'p12_15', english: 'Hooray!', chinese: '好耶/万岁', pos: PartOfSpeech.Other },
  { id: 'p12_16', english: 'take a photo', chinese: '拍照', pos: PartOfSpeech.Other },
  { id: 'p12_17', english: 'please', chinese: '请', pos: PartOfSpeech.Other },
  { id: 'p12_18', english: 'Well done!', chinese: '干得好', pos: PartOfSpeech.Other },

  // --- Page 13: Numbers (数词) ---
  { id: 'p13_1', english: 'one', chinese: '一', pos: PartOfSpeech.Number },
  { id: 'p13_2', english: 'two', chinese: '二', pos: PartOfSpeech.Number },
  { id: 'p13_3', english: 'three', chinese: '三', pos: PartOfSpeech.Number },
  { id: 'p13_4', english: 'four', chinese: '四', pos: PartOfSpeech.Number },
  { id: 'p13_5', english: 'five', chinese: '五', pos: PartOfSpeech.Number },
  { id: 'p13_6', english: 'six', chinese: '六', pos: PartOfSpeech.Number },
];